# docker-compose.yml

version: '3.8'

services:
  web:
    image: nudity:latest
    container_name: nudity
    build:
      context: .
      dockerfile: Dockerfile.prod
    volumes:
      - ./app:/app
    ports:
      - "80:80"
