# docker-compose.yml

version: '3.8'

services:
  web:
    image: nudity:latest
    container_name: nudity
    build: .
    command: uvicorn main:app --host 0.0.0.0 --port 80
    volumes:
      - ./app:/app
    ports:
      - "80:80"