name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    environment: prod
    runs-on: ubuntu-latest
    env:
    - DOCKERHUB_ACCESS_KEY: ${{secrets.DOCKERHUB_ACCESS_KEY}}
    - DOCKERHUB_USERNAME: ${{secrets.DOCKERHUB_USERNAME}}
    steps:
    - uses: actions/checkout@v2
    - name: Dokcer Hub login
      run: docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_ACCESS_KEY
    
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: ./
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/nudity:latest    
