name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    environment: prod
    env:
      DOCKERHUB_ACCESS_KEY: ${{secrets.DOCKERHUB_ACCESS_KEY}}
      DOCKERHUB_USERNAME: ${{secrets.DOCKERHUB_USERNAME}}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Dokcer Hub login

      run: docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_ACCESS_KEY
    
    - name: Build the Docker image
      run: docker-compose up -d --build
    
    - name: Push image
      run: docker push ${{secrets.DOCKERHUB_USERNAME}}/nudity:latest
